"""Built-in default Shape_Library / Line_Rules — ported 1:1 from the JS
playground's SHAPES/LINES tables so the backend palette, template
generator, and outline mode all have the same ~40+ entity/relation types
available without requiring the user's workbook to define them.
"""
from .model import ShapeDef, LineDef

DEFAULT_SHAPES: dict[str, ShapeDef] = {
    'business_actor': ShapeDef(entity_type='business_actor', family='EA', shape='rectangle',
        default_w=120.0, default_h=50.0, min_w=100.0, min_h=40.0,
        fill='#FFFFB5', stroke='#B8B800', auto='Y'),
    'business_role': ShapeDef(entity_type='business_role', family='EA', shape='rectangle',
        default_w=120.0, default_h=50.0, min_w=100.0, min_h=40.0,
        fill='#FFFFB5', stroke='#B8B800', auto='Y'),
    'business_process': ShapeDef(entity_type='business_process', family='EA', shape='rounded rectangle',
        default_w=140.0, default_h=50.0, min_w=100.0, min_h=40.0,
        fill='#FFFFB5', stroke='#B8B800', auto='Y'),
    'business_service': ShapeDef(entity_type='business_service', family='EA', shape='rounded rectangle',
        default_w=140.0, default_h=50.0, min_w=100.0, min_h=40.0,
        fill='#FFFFB5', stroke='#B8B800', auto='Y'),
    'business_object': ShapeDef(entity_type='business_object', family='EA', shape='title band',
        default_w=120.0, default_h=55.0, min_w=100.0, min_h=45.0,
        fill='#FFFFB5', stroke='#B8B800', auto='Y'),
    'business_event': ShapeDef(entity_type='business_event', family='EA', shape='rounded rectangle',
        default_w=120.0, default_h=45.0, min_w=100.0, min_h=40.0,
        fill='#FFFFB5', stroke='#B8B800', auto='Y'),
    'capability': ShapeDef(entity_type='capability', family='EA', shape='rectangle',
        default_w=160.0, default_h=60.0, min_w=120.0, min_h=50.0,
        fill='#FFFFB5', stroke='#B8B800', auto='Y'),
    'value_stream': ShapeDef(entity_type='value_stream', family='EA', shape='chevron',
        default_w=160.0, default_h=55.0, min_w=120.0, min_h=45.0,
        fill='#FFFFB5', stroke='#B8B800', auto='Y'),
    'goal': ShapeDef(entity_type='goal', family='EA', shape='rounded rectangle',
        default_w=130.0, default_h=50.0, min_w=100.0, min_h=40.0,
        fill='#E8D5E8', stroke='#9E6B9E', auto='Y'),
    'outcome': ShapeDef(entity_type='outcome', family='EA', shape='rounded rectangle',
        default_w=130.0, default_h=50.0, min_w=100.0, min_h=40.0,
        fill='#E8D5E8', stroke='#9E6B9E', auto='Y'),
    'stakeholder': ShapeDef(entity_type='stakeholder', family='EA', shape='rounded rectangle',
        default_w=130.0, default_h=50.0, min_w=100.0, min_h=40.0,
        fill='#E8D5E8', stroke='#9E6B9E', auto='Y'),
    'application_component': ShapeDef(entity_type='application_component', family='EA', shape='rectangle',
        default_w=150.0, default_h=55.0, min_w=110.0, min_h=45.0,
        fill='#B5E3F7', stroke='#4A90B8', auto='Y'),
    'application_service': ShapeDef(entity_type='application_service', family='EA', shape='rounded rectangle',
        default_w=150.0, default_h=50.0, min_w=110.0, min_h=40.0,
        fill='#B5E3F7', stroke='#4A90B8', auto='Y'),
    'application_interface': ShapeDef(entity_type='application_interface', family='EA', shape='rectangle',
        default_w=140.0, default_h=50.0, min_w=100.0, min_h=40.0,
        fill='#B5E3F7', stroke='#4A90B8', auto='Y'),
    'data_object': ShapeDef(entity_type='data_object', family='EA', shape='title band',
        default_w=120.0, default_h=55.0, min_w=100.0, min_h=45.0,
        fill='#B5E3F7', stroke='#4A90B8', auto='Y'),
    'node': ShapeDef(entity_type='node', family='EA', shape='3d box',
        default_w=140.0, default_h=60.0, min_w=110.0, min_h=50.0,
        fill='#C9E7C9', stroke='#5E9C5E', auto='Y'),
    'device': ShapeDef(entity_type='device', family='EA', shape='3d box',
        default_w=140.0, default_h=60.0, min_w=110.0, min_h=50.0,
        fill='#C9E7C9', stroke='#5E9C5E', auto='Y'),
    'technology_service': ShapeDef(entity_type='technology_service', family='EA', shape='rounded rectangle',
        default_w=150.0, default_h=50.0, min_w=110.0, min_h=40.0,
        fill='#C9E7C9', stroke='#5E9C5E', auto='Y'),
    'artifact': ShapeDef(entity_type='artifact', family='EA', shape='rectangle',
        default_w=120.0, default_h=50.0, min_w=90.0, min_h=40.0,
        fill='#C9E7C9', stroke='#5E9C5E', auto='Y'),
    'group': ShapeDef(entity_type='group', family='EA', shape='container',
        default_w=400.0, default_h=300.0, min_w=200.0, min_h=150.0,
        fill='#FFFFFF', stroke='#808080', auto='container'),
    'start_end': ShapeDef(entity_type='start_end', family='Flowchart', shape='stadium',
        default_w=100.0, default_h=40.0, min_w=80.0, min_h=36.0,
        fill='#D5E8D4', stroke='#82B366', auto='Y'),
    'process': ShapeDef(entity_type='process', family='Flowchart', shape='rectangle',
        default_w=140.0, default_h=50.0, min_w=100.0, min_h=40.0,
        fill='#DAE8FC', stroke='#6C8EBF', auto='Y'),
    'decision': ShapeDef(entity_type='decision', family='Flowchart', shape='diamond',
        default_w=140.0, default_h=80.0, min_w=120.0, min_h=70.0,
        fill='#FFE6CC', stroke='#D79B00', auto='Y'),
    'data_io': ShapeDef(entity_type='data_io', family='Flowchart', shape='parallelogram',
        default_w=130.0, default_h=50.0, min_w=100.0, min_h=40.0,
        fill='#F8CECC', stroke='#B85450', auto='Y'),
    'document': ShapeDef(entity_type='document', family='Flowchart', shape='wavy bottom',
        default_w=120.0, default_h=60.0, min_w=100.0, min_h=50.0,
        fill='#FFF2CC', stroke='#D6B656', auto='Y'),
    'database': ShapeDef(entity_type='database', family='Flowchart', shape='cylinder',
        default_w=90.0, default_h=60.0, min_w=70.0, min_h=50.0,
        fill='#E1D5E7', stroke='#9673A6', auto='Y'),
    'subprocess': ShapeDef(entity_type='subprocess', family='Flowchart', shape='rectangle',
        default_w=150.0, default_h=50.0, min_w=110.0, min_h=40.0,
        fill='#DAE8FC', stroke='#6C8EBF', auto='Y'),
    'connector': ShapeDef(entity_type='connector', family='Flowchart', shape='circle',
        default_w=36.0, default_h=36.0, min_w=30.0, min_h=30.0,
        fill='#FFFFFF', stroke='#666666', auto='N'),
    'lane': ShapeDef(entity_type='lane', family='Flowchart', shape='container',
        default_w=900.0, default_h=160.0, min_w=400.0, min_h=120.0,
        fill='#F5F5F5', stroke='#666666', auto='container'),
    'person_card': ShapeDef(entity_type='person_card', family='OrgChart', shape='rounded rectangle',
        default_w=170.0, default_h=64.0, min_w=150.0, min_h=56.0,
        fill='#FFFFFF', stroke='#4472C4', auto='N'),
    'department': ShapeDef(entity_type='department', family='OrgChart', shape='container',
        default_w=400.0, default_h=300.0, min_w=200.0, min_h=120.0,
        fill='#F2F7FF', stroke='#8FAADC', auto='container'),
    'cloud': ShapeDef(entity_type='cloud', family='Network', shape='cloud',
        default_w=140.0, default_h=80.0, min_w=110.0, min_h=60.0,
        fill='#F5F5F5', stroke='#666666', auto='N'),
    'firewall': ShapeDef(entity_type='firewall', family='Network', shape='rectangle',
        default_w=110.0, default_h=60.0, min_w=90.0, min_h=50.0,
        fill='#F8CECC', stroke='#B85450', auto='N'),
    'router': ShapeDef(entity_type='router', family='Network', shape='circle',
        default_w=70.0, default_h=70.0, min_w=60.0, min_h=60.0,
        fill='#DAE8FC', stroke='#6C8EBF', auto='N'),
    'switch': ShapeDef(entity_type='switch', family='Network', shape='rectangle',
        default_w=100.0, default_h=50.0, min_w=80.0, min_h=40.0,
        fill='#DAE8FC', stroke='#6C8EBF', auto='N'),
    'load_balancer': ShapeDef(entity_type='load_balancer', family='Network', shape='rectangle',
        default_w=110.0, default_h=55.0, min_w=90.0, min_h=45.0,
        fill='#D5E8D4', stroke='#82B366', auto='N'),
    'server': ShapeDef(entity_type='server', family='Network', shape='rectangle',
        default_w=120.0, default_h=60.0, min_w=100.0, min_h=50.0,
        fill='#E1D5E7', stroke='#9673A6', auto='N'),
    'zone': ShapeDef(entity_type='zone', family='Network', shape='container',
        default_w=600.0, default_h=220.0, min_w=300.0, min_h=150.0,
        fill='#FBFBFB', stroke='#999999', auto='container'),
    'entity': ShapeDef(entity_type='entity', family='ERD', shape='rows',
        default_w=180.0, default_h=30.0, min_w=160.0, min_h=30.0,
        fill='#FFFFFF', stroke='#333333', auto='rows'),
    'view': ShapeDef(entity_type='view', family='ERD', shape='rows',
        default_w=180.0, default_h=30.0, min_w=160.0, min_h=30.0,
        fill='#FAFAFA', stroke='#777777', auto='rows'),
    'battery': ShapeDef(entity_type='battery', family='Wiring', shape='rows',
        default_w=180.0, default_h=30.0, min_w=160.0, min_h=30.0,
        fill='#FFF2CC', stroke='#B45309', auto='rows'),
    'fuse_block': ShapeDef(entity_type='fuse_block', family='Wiring', shape='rows',
        default_w=180.0, default_h=30.0, min_w=160.0, min_h=30.0,
        fill='#F8CECC', stroke='#B85450', auto='rows'),
    'e_stop': ShapeDef(entity_type='e_stop', family='Wiring', shape='rows',
        default_w=180.0, default_h=30.0, min_w=160.0, min_h=30.0,
        fill='#F8CECC', stroke='#CC0000', auto='rows'),
    'dcdc_converter': ShapeDef(entity_type='dcdc_converter', family='Wiring', shape='rows',
        default_w=180.0, default_h=30.0, min_w=160.0, min_h=30.0,
        fill='#FFF2CC', stroke='#D6B656', auto='rows'),
    'controller': ShapeDef(entity_type='controller', family='Wiring', shape='rows',
        default_w=180.0, default_h=30.0, min_w=160.0, min_h=30.0,
        fill='#DAE8FC', stroke='#2B5797', auto='rows'),
    'motor_driver': ShapeDef(entity_type='motor_driver', family='Wiring', shape='rows',
        default_w=180.0, default_h=30.0, min_w=160.0, min_h=30.0,
        fill='#E1D5E7', stroke='#7A5C99', auto='rows'),
    'motor': ShapeDef(entity_type='motor', family='Wiring', shape='rows',
        default_w=180.0, default_h=30.0, min_w=160.0, min_h=30.0,
        fill='#E1D5E7', stroke='#9673A6', auto='rows'),
    'sensor': ShapeDef(entity_type='sensor', family='Wiring', shape='rows',
        default_w=180.0, default_h=30.0, min_w=160.0, min_h=30.0,
        fill='#D5E8D4', stroke='#82B366', auto='rows'),
    'eth_switch': ShapeDef(entity_type='eth_switch', family='Wiring', shape='rows',
        default_w=180.0, default_h=30.0, min_w=160.0, min_h=30.0,
        fill='#DAE8FC', stroke='#6C8EBF', auto='rows'),
    'junction': ShapeDef(entity_type='junction', family='Wiring', shape='rows',
        default_w=160.0, default_h=30.0, min_w=140.0, min_h=30.0,
        fill='#FFFFFF', stroke='#666666', auto='rows'),
}

DEFAULT_LINES: dict[str, LineDef] = {
    'composition': LineDef(relation_type='composition', family='EA', style='solid',
        width=1.0, source_end='filled diamond', target_end='none',
        routing='orthogonal', label_pos='mid', color='#333333'),
    'aggregation': LineDef(relation_type='aggregation', family='EA', style='solid',
        width=1.0, source_end='open diamond', target_end='none',
        routing='orthogonal', label_pos='mid', color='#333333'),
    'assignment': LineDef(relation_type='assignment', family='EA', style='solid',
        width=1.0, source_end='filled ball', target_end='open arrow',
        routing='orthogonal', label_pos='mid', color='#333333'),
    'realization': LineDef(relation_type='realization', family='EA', style='dashed',
        width=1.0, source_end='none', target_end='hollow triangle',
        routing='orthogonal', label_pos='mid', color='#333333'),
    'serving': LineDef(relation_type='serving', family='EA', style='solid',
        width=1.0, source_end='none', target_end='open arrow',
        routing='orthogonal', label_pos='mid', color='#333333'),
    'access': LineDef(relation_type='access', family='EA', style='dotted',
        width=1.0, source_end='none', target_end='open arrow',
        routing='orthogonal', label_pos='mid', color='#333333'),
    'triggering': LineDef(relation_type='triggering', family='EA', style='solid',
        width=1.0, source_end='none', target_end='filled arrow',
        routing='orthogonal', label_pos='mid', color='#333333'),
    'flow': LineDef(relation_type='flow', family='EA', style='dashed',
        width=1.0, source_end='none', target_end='filled arrow',
        routing='orthogonal', label_pos='mid', color='#333333'),
    'association': LineDef(relation_type='association', family='EA', style='solid',
        width=1.0, source_end='none', target_end='none',
        routing='straight', label_pos='mid', color='#333333'),
    'specialization': LineDef(relation_type='specialization', family='EA', style='solid',
        width=1.0, source_end='none', target_end='hollow triangle',
        routing='orthogonal', label_pos='mid', color='#333333'),
    'sequence_flow': LineDef(relation_type='sequence_flow', family='Flowchart', style='solid',
        width=1.0, source_end='none', target_end='filled arrow',
        routing='orthogonal', label_pos='near source', color='#333333'),
    'message_flow': LineDef(relation_type='message_flow', family='Flowchart', style='dashed',
        width=1.0, source_end='open circle', target_end='open arrow',
        routing='orthogonal', label_pos='mid', color='#666666'),
    'reports_to': LineDef(relation_type='reports_to', family='OrgChart', style='solid',
        width=1.0, source_end='none', target_end='none',
        routing='orthogonal', label_pos='mid', color='#4472C4'),
    'dotted_reporting': LineDef(relation_type='dotted_reporting', family='OrgChart', style='dashed',
        width=1.0, source_end='none', target_end='none',
        routing='orthogonal', label_pos='mid', color='#999999'),
    'physical_link': LineDef(relation_type='physical_link', family='Network', style='solid',
        width=2.0, source_end='none', target_end='none',
        routing='straight', label_pos='mid', color='#333333'),
    'logical_link': LineDef(relation_type='logical_link', family='Network', style='dashed',
        width=1.0, source_end='none', target_end='none',
        routing='straight', label_pos='mid', color='#6C8EBF'),
    'vpn_tunnel': LineDef(relation_type='vpn_tunnel', family='Network', style='dash-dot',
        width=2.0, source_end='none', target_end='none',
        routing='straight', label_pos='mid', color='#9673A6'),
    'one_to_many': LineDef(relation_type='one_to_many', family='ERD', style='solid',
        width=1.0, source_end='single tick', target_end="crow's foot",
        routing='orthogonal', label_pos='mid', color='#333333'),
    'one_to_one': LineDef(relation_type='one_to_one', family='ERD', style='solid',
        width=1.0, source_end='single tick', target_end='single tick',
        routing='orthogonal', label_pos='mid', color='#333333'),
    'many_to_many': LineDef(relation_type='many_to_many', family='ERD', style='solid',
        width=1.0, source_end="crow's foot", target_end="crow's foot",
        routing='orthogonal', label_pos='mid', color='#333333'),
    'data_flow': LineDef(relation_type='data_flow', family='ERD', style='solid',
        width=1.0, source_end='none', target_end='filled arrow',
        routing='orthogonal', label_pos='mid', color='#4472C4'),
    'power_wire': LineDef(relation_type='power_wire', family='Wiring', style='solid',
        width=2.5, source_end='none', target_end='none',
        routing='orthogonal', label_pos='mid', color='#CC0000'),
    'ground_wire': LineDef(relation_type='ground_wire', family='Wiring', style='solid',
        width=2.5, source_end='none', target_end='none',
        routing='orthogonal', label_pos='mid', color='#111111'),
    'signal_wire': LineDef(relation_type='signal_wire', family='Wiring', style='solid',
        width=1.2, source_end='none', target_end='open arrow',
        routing='orthogonal', label_pos='mid', color='#1A73E8'),
    'can_bus': LineDef(relation_type='can_bus', family='Wiring', style='dashed',
        width=2.0, source_end='none', target_end='none',
        routing='orthogonal', label_pos='mid', color='#2E7D32'),
    'eth_cable': LineDef(relation_type='eth_cable', family='Wiring', style='solid',
        width=2.0, source_end='none', target_end='none',
        routing='orthogonal', label_pos='mid', color='#F9AB00'),
}
